### ISSUE TITLE
gem install hermann -v '0.20.1' failing

### ISSUE THREAD

**Issue by sdaswani-lookout** [lookout/hermann#85] opened 2015-03-26 21:02 UTC
I'm trying to install the hermann gem on OS X Yosemite Version 10.10.2, but it isn't working :( .

```
gem install hermann -v '0.20.1'
Building native extensions.  This could take a while...
ERROR:  Error installing hermann:
	ERROR: Failed to build gem native extension.

    /Users/sdaswani/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -r ./siteconf20150326-6859-16ln9w0.rb extconf.rb
Library Dir: /Users/sdaswani/.rvm/rubies/ruby-1.9.3-p551/lib
Include Dir: /Users/sdaswani/.rvm/rubies/ruby-1.9.3-p551/include
Downloading 0.8.4.tar.gz (100%) ding 0.8.4.tar.gz 
Extracting 0.8.4.tar.gz into tmp/i686-apple-darwin11/ports/librdkafka/0.8.4... OK
Running git apply with /Users/sdaswani/.rvm/gems/ruby-1.9.3-p551/gems/hermann-0.20.1/ext/patches/librdkafka/0006-Update-some-headers-to-include-the-right-headers-to-.patch...
Running 'patch' for librdkafka 0.8.4... OK
Running 'configure' for librdkafka 0.8.4... OK
Running 'compile' for librdkafka 0.8.4... OK
Running 'install' for librdkafka 0.8.4... OK
Activating librdkafka 0.8.4 (from ports/i686-apple-darwin11/librdkafka/0.8.4)...
creating Makefile

make  clean

make
compiling hermann_lib.c
couldn't understand kern.osversion `14.1.0'
hermann_lib.c: In function ‘msg_delivered’:
hermann_lib.c:118: warning: comparison between pointer and integer
hermann_lib.c: In function ‘consumer_consume’:
hermann_lib.c:411: warning: format not a string literal and no format arguments
hermann_lib.c: In function ‘producer_push_single’:
hermann_lib.c:555: warning: assignment makes integer from pointer without a cast
hermann_lib.c: In function ‘producer_tick’:
hermann_lib.c:646: warning: format not a string literal and no format arguments
hermann_lib.c: In function ‘producer_connect’:
hermann_lib.c:670: warning: passing argument 4 of ‘rd_kafka_metadata’ from incompatible pointer type
linking shared-object hermann/hermann_lib.bundle
couldn't understand kern.osversion `14.1.0'
ld: targeted OS version does not support use of thread local variables in _rd_kafka_op_reply for architecture x86_64
collect2: ld returned 1 exit status
make: *** [hermann_lib.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/sdaswani/.rvm/gems/ruby-1.9.3-p551/gems/hermann-0.20.1 for inspection.
Results logged to /Users/sdaswani/.rvm/gems/ruby-1.9.3-p551/extensions/x86_64-darwin-14/1.9.1/hermann-0.20.1/gem_make.out
```

**Comment by rtyler** [comment] 2015-03-26 21:28
For additional context, since @sdaswani-lookout and I discussed this over IM. He can in fact build librdkafka 0.8.4 standalone on his machine

**Comment by rtyler** [comment] 2015-09-28 15:39
Without a reproduction case, I'm going to close this for now. We're on a newer version of librdkafka and I've not seen other similar reports.

@sdaswani-lookout let me know if you find this behavior still exists with the current released version

**Closed by rtyler** 2015-09-28 15:39 UTC
Labels: bug, MRI
